const state={category:"gex_full",data:null,zoom:1,profileHover:null,historyHover:null};
const $=id=>document.getElementById(id);
const number=value=>Number.isFinite(Number(value))?Number(value):null;
const fmt=value=>number(value)==null?"—":new Intl.NumberFormat("en-US",{maximumFractionDigits:2}).format(Number(value));
const easternDate=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/New_York",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
$("session-date").value=easternDate();

async function load(){
  const date=$("session-date").value||easternDate();
  const response=await fetch(`/gex/data?category=${encodeURIComponent(state.category)}&date=${encodeURIComponent(date)}`,{cache:"no-store"});
  const payload=await response.json().catch(()=>null);
  if(!response.ok)throw new Error(payload?.error||"Dashboard data unavailable");
  state.data=payload;state.profileHover=null;state.historyHover=null;updateText();drawAll();
}
function updateText(){
  const latest=state.data?.latest, schedule=state.data?.schedule;
  $("collection-status").textContent=`SPX · ${schedule?.start||"09:00"}–${schedule?.end||"16:00"} ET · every ${schedule?.cadence_seconds||30}s`;
  $("metric-spot").textContent=fmt(latest?.spot);$("metric-zero").textContent=fmt(latest?.zero_gamma);
  $("metric-pos").textContent=fmt(latest?.major_pos_vol??latest?.major_pos_oi);$("metric-neg").textContent=fmt(latest?.major_neg_vol??latest?.major_neg_oi);
  $("metric-time").textContent=latest?.observed_at?new Date(latest.observed_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit",second:"2-digit"}):"Waiting";
  $("sample-count").textContent=`${state.data?.history?.length||0} samples`;
  $("empty-note").classList.toggle("hidden",Boolean(state.data?.history?.length));
  $("chart-title").textContent=`SPX Gamma Exposure · ${state.category==="gex_full"?"Full":state.category==="gex_zero"?"0DTE":"1DTE"}`;
}
function resize(canvas){const box=canvas.getBoundingClientRect(),dpr=devicePixelRatio||1,w=Math.max(1,Math.round(box.width*dpr)),h=Math.max(1,Math.round(box.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}const c=canvas.getContext("2d");c.setTransform(dpr,0,0,dpr,0,0);return{c,w:box.width,h:box.height}}
function line(c,x1,y1,x2,y2,color,width=1,dash=[]){c.save();c.strokeStyle=color;c.lineWidth=width;c.setLineDash(dash);c.beginPath();c.moveTo(x1,y1);c.lineTo(x2,y2);c.stroke();c.restore()}
function label(c,text,x,y,align="left",color="#8ba99a",size=11){c.fillStyle=color;c.font=`${size}px ui-monospace,SFMono-Regular,Menlo,monospace`;c.textAlign=align;c.fillText(text,x,y)}
function drawProfile(){const canvas=$("profile-chart"),{c,w,h}=resize(canvas);c.clearRect(0,0,w,h);c.fillStyle="#030705";c.fillRect(0,0,w,h);const latest=state.data?.latest;const rows=(latest?.strikes||[]).filter(row=>Array.isArray(row)&&number(row[0])!=null);if(!rows.length){label(c,"No profile snapshot for this session",w/2,h/2,"center","#7f9e91",14);return}const spot=number(latest.spot),zero=number(latest.zero_gamma);const anchor=spot??zero??number(rows[Math.floor(rows.length/2)][0]);const allStrikes=rows.map(r=>number(r[0]));const half=Math.max(25,(Math.max(...allStrikes)-Math.min(...allStrikes))/2/state.zoom);const min=anchor-half,max=anchor+half;const visible=rows.filter(r=>number(r[0])>=min&&number(r[0])<=max);const pad={l:70,r:26,t:24,b:34},pw=w-pad.l-pad.r,ph=h-pad.t-pad.b;const maxGex=Math.max(1,...visible.flatMap(r=>[Math.abs(number(r[1])||0),Math.abs(number(r[2])||0)]));const center=pad.l+pw*.5;const y=strike=>pad.t+(max-strike)/(max-min)*ph;const x=gex=>center+gex/maxGex*pw*.47;c.fillStyle="#06100c";c.fillRect(pad.l,pad.t,pw,ph);for(let i=0;i<=6;i++){const strike=min+(max-min)*i/6,yy=y(strike);line(c,pad.l,yy,pad.l+pw,yy,"#1a352a");label(c,fmt(strike),pad.l-8,yy+4,"right")}line(c,center,pad.t,center,pad.t+ph,"#2b5441");label(c,"− GEX",pad.l,pad.t-7,"left");label(c,"GEX +",pad.l+pw,pad.t-7,"right");for(const row of visible){const strike=number(row[0]),oi=number(row[1])||0,vol=number(row[2])||0,yy=y(strike),bar=Math.max(2,ph/visible.length*.66);c.fillStyle=oi>=0?"#42c87c":"#e34f55";c.fillRect(Math.min(center,x(oi)),yy-bar/2,Math.abs(x(oi)-center),bar);c.fillStyle=vol>=0?"#a3e55d":"#ff8c82";c.globalAlpha=.8;c.fillRect(Math.min(center,x(vol)),yy+bar*.1,Math.abs(x(vol)-center),Math.max(1,bar*.34));c.globalAlpha=1}for(const [value,color,name] of [[zero,"#e3c56b","Zero gamma"],[spot,"#20d9e6","Spot"]])if(value!=null&&value>=min&&value<=max){const yy=y(value);line(c,pad.l,yy,pad.l+pw,yy,color,1.3,[5,4]);label(c,`${name} ${fmt(value)}`,pad.l+pw-4,yy-5,"right",color)}if(state.profileHover){const hit=nearestStrike(visible,state.profileHover.strike);if(hit){const yy=y(number(hit[0]));line(c,pad.l,yy,pad.l+pw,yy,"#dfffee",1,[2,3])}}}
function nearestStrike(rows,strike){return rows.reduce((best,row)=>!best||Math.abs(number(row[0])-strike)<Math.abs(number(best[0])-strike)?row:best,null)}
function drawHistory(){const canvas=$("history-chart"),{c,w,h}=resize(canvas);c.clearRect(0,0,w,h);c.fillStyle="#030705";c.fillRect(0,0,w,h);const series=(state.data?.history||[]).filter(p=>number(p.spot)!=null);if(!series.length){label(c,"No intraday history for this session",w/2,h/2,"center","#7f9e91",14);return}const pad={l:58,r:18,t:18,b:32},pw=w-pad.l-pad.r,ph=h-pad.t-pad.b;const times=series.map(p=>new Date(p.observed_at).getTime()),values=series.flatMap(p=>[number(p.spot),number(p.zero_gamma),number(p.major_pos_vol),number(p.major_neg_vol)]).filter(v=>v!=null);let lo=Math.min(...values),hi=Math.max(...values),extra=Math.max(3,(hi-lo)*.08);lo-=extra;hi+=extra;const x=t=>pad.l+(t-times[0])/(Math.max(1,times.at(-1)-times[0]))*pw,y=v=>pad.t+(hi-v)/(hi-lo)*ph;for(let i=0;i<=4;i++){const value=lo+(hi-lo)*i/4,yy=y(value);line(c,pad.l,yy,pad.l+pw,yy,"#1a352a");label(c,fmt(value),pad.l-7,yy+4,"right")}for(let i=0;i<=4;i++){const t=times[0]+(times.at(-1)-times[0])*i/4,xx=x(t);line(c,xx,pad.t,xx,pad.t+ph,"#14281f");label(c,new Date(t).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"}),xx,h-10,"center")}const path=(key,color,dash=[])=>{c.save();c.strokeStyle=color;c.lineWidth=1.5;c.setLineDash(dash);c.beginPath();series.forEach((p,i)=>{const xx=x(new Date(p.observed_at).getTime()),yy=y(number(p[key]));if(i===0)c.moveTo(xx,yy);else c.lineTo(xx,yy)});c.stroke();c.restore()};path("spot","#20d9e6");if(series.some(p=>number(p.zero_gamma)!=null))path("zero_gamma","#e3c56b",[5,4]);if(series.some(p=>number(p.major_pos_vol)!=null))path("major_pos_vol","#70d695",[2,4]);if(series.some(p=>number(p.major_neg_vol)!=null))path("major_neg_vol","#ef6e74",[2,4]);if(state.historyHover){const p=series[state.historyHover.index];const xx=x(new Date(p.observed_at).getTime());line(c,xx,pad.t,xx,pad.t+ph,"#e5fff0",1,[3,3])}}
function drawAll(){drawProfile();drawHistory()}
function tooltip(id,event,text){const el=$(id),box=event.currentTarget.getBoundingClientRect();el.textContent=text;el.style.left=`${Math.min(box.width-150,Math.max(6,event.clientX-box.left+12))}px`;el.style.top=`${Math.max(6,event.clientY-box.top+12)}px`;el.classList.remove("hidden")}
$("profile-chart").addEventListener("pointermove",event=>{const latest=state.data?.latest,rows=(latest?.strikes||[]).filter(r=>number(r[0])!=null);if(!rows.length)return;const box=event.currentTarget.getBoundingClientRect(),anchor=number(latest.spot)??number(latest.zero_gamma)??number(rows[0][0]),half=Math.max(25,(Math.max(...rows.map(r=>number(r[0])))-Math.min(...rows.map(r=>number(r[0]))))/2/state.zoom),strike=anchor+half-(event.clientY-box.top-24)/Math.max(1,box.height-58)*(half*2),hit=nearestStrike(rows,strike);state.profileHover={strike:number(hit[0])};tooltip("profile-tooltip",event,`Strike ${fmt(hit[0])}\nOI GEX  ${fmt(hit[1])}\nVOL GEX ${fmt(hit[2])}`);drawProfile()});
$("profile-chart").addEventListener("pointerleave",()=>{$("profile-tooltip").classList.add("hidden");state.profileHover=null;drawProfile()});
$("profile-chart").addEventListener("wheel",event=>{event.preventDefault();state.zoom=Math.min(8,Math.max(.6,state.zoom*(event.deltaY<0?1.18:.85)));drawProfile()},{passive:false});
$("history-chart").addEventListener("pointermove",event=>{const series=state.data?.history||[];if(!series.length)return;const box=event.currentTarget.getBoundingClientRect(),ratio=Math.max(0,Math.min(1,(event.clientX-box.left-58)/Math.max(1,box.width-76))),index=Math.round(ratio*(series.length-1)),p=series[index];state.historyHover={index};tooltip("history-tooltip",event,`${new Date(p.observed_at).toLocaleTimeString()}\nSpot       ${fmt(p.spot)}\nZero γ     ${fmt(p.zero_gamma)}\nMajor +γ   ${fmt(p.major_pos_vol)}\nMajor −γ   ${fmt(p.major_neg_vol)}`);drawHistory()});
$("history-chart").addEventListener("pointerleave",()=>{$("history-tooltip").classList.add("hidden");state.historyHover=null;drawHistory()});
document.querySelectorAll(".tab").forEach(button=>button.addEventListener("click",async()=>{state.category=button.dataset.category;document.querySelectorAll(".tab").forEach(tab=>{const active=tab===button;tab.classList.toggle("active",active);tab.setAttribute("aria-selected",String(active))});try{await load()}catch(error){$("collection-status").textContent=error.message}}));
$("session-date").addEventListener("change",()=>load().catch(error=>$("collection-status").textContent=error.message));
window.addEventListener("resize",drawAll);load().catch(error=>$("collection-status").textContent=error.message);setInterval(()=>load().catch(()=>null),30000);
